### ISSUE TITLE
Deploy on Kubernetes || Unknown Error from command nft list table inet firezone

### ISSUE THREAD

**Issue by Mhm0ud** [firezone/firezone#2800]
**Describe the bug**
I am trying to deploy the firezone in a Kubernetes cluster with this yaml file:
```

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firezone-data-pvc
  namespace: firezone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: firezone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firezone-deployment
  namespace: firezone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firezone
  template:
    metadata:
      labels:
        app: firezone
    spec:
      containers:
      - name: firezone
        image: firezone/firezone:0.7.36
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 51820
          protocol: UDP
        env:
        - name: WIREGUARD_IPV6_ENABLED	
          value: "false"
        - name: WIREGUARD_IPV6_MASQUERADE
          value: "false"
        - name: DEFAULT_ADMIN_EMAIL
          value: "myemail@test.test"
        - name: DEFAULT_ADMIN_PASSWORD
          value: password
        - name: EXTERNAL_URL
          value: "http://firezone2.test.test"
        - name: SECRET_KEY_BASE
          value: "4fdd28c365ca216d8fd74a6e0943
        - name: LIVE_VIEW_SIGNING_SALT
          value: "GWkILJaYeT
        - name: COOKIE_SIGNING_SALT
          value: "gD+MRbTiDiI
        - name: COOKIE_ENCRYPTION_SALT
          value: "J1KHjzDQ2r
        - name: GUARDIAN_SECRET_KEY
          value: "4692c00f2d4600576ca73c4
        - name: DATABASE_ENCRYPTION_KEY
          value: "e9e22c3ee300182b88
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: firezone
        - name: DATABASE_USER
          value: usernameu98fj9832j89fh98h
        - name: DATABASE_PASSWORD
          value: password09uf98whcj
        volumeMounts:
        - mountPath: /var/lib/firezone
          name: firezone-data
        - mountPath: /var/firezone
          name: firezone-saml
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
      volumes:
      - name: firezone-data
        persistentVolumeClaim:
          claimName: firezone-data-pvc
      - name: firezone-saml
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: firezone-service
  namespace: firezone
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 13000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 13000
  - name: custom-udp
    protocol: UDP
    port: 51820
    targetPort: 51820
  selector:
    app: firezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: firezone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: usernameu98fj9832j89fh98h
        - name: POSTGRES_PASSWORD
          value: password09uf98whcj
        - name: POSTGRES_DB
          value: firezone
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata_firezone"  # Use a subdirectory for data
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: firezone
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: postgres
```

But the Firezone pod can't start with the following error:

```
20:13:53.068 erl_level=notice domain=otp file=application_controller.erl function=info_exited/3 line=2119 mfa=:application_controller.info_exited/3 module=application_controller pid=<0.44.0> [notice] Application fz_wall exited: FzWall.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzWall.Server
    ** (EXIT) an exception was raised:
        ** (RuntimeError)   Unknown Error from command nft list table inet firezone. Error:
  

            (fz_wall 0.7.36) lib/fz_wall/cli/helpers/nft.ex:188: FzWall.CLI.Helpers.Nft.table_exists?/0
            (fz_wall 0.7.36) lib/fz_wall/cli/helpers/nft.ex:168: FzWall.CLI.Helpers.Nft.teardown_table/0
            (fz_wall 0.7.36) lib/fz_wall/cli/live.ex:15: FzWall.CLI.Live.setup_firewall/0
            (fz_wall 0.7.36) lib/fz_wall/server.ex:16: FzWall.Server.init/1
            (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.2) gen_server.erl:814: :gen_server.init_it/6
            (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"  Unknown Error from command nft list table inet firezone. Error:\n  \n\">>},[{'Elixir.FzWall.CLI.Helpers.Nft','table_exists?',0,[{file,\"lib/fz_wall/cli/helpers/nft.ex\"},{line,188},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzWall.CLI.Helpers.Nft',teardown_table,0,[{file,\"lib/fz_wall/cli/helpers/nft.ex\"},{line,168}]},{'Elixir.FzWall.CLI.Live',setup_firewall,0,[{file,\"lib/fz_wall/cli/live.ex\"},{line,15}]},{'Elixir.FzWall.Server',init,1,[{file,\"lib/fz_wall/server.ex\"},{line,16}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"  Unknown Error from command nft list table inet firezone. Error:\n  \n">>},[{'Elixir.FzWall.CLI.Helpers.Nft','table_exists?',0,[{file,"lib/fz_wall/cli/helpers/nft.ex"},{line,188},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzWall.CLI.Helpers.Nft',teardown_table,0,[{file,"lib/fz_wall/cli/helpers/nft.ex"},{line,168}]},{'Elixir.FzWall.CLI.Live',setup_firewall,0,[{file,"lib/fz_wall/cli/live.ex"},{line,15}]},{'Elixir.FzWall.Server',init,1,[{file,"lib/fz_wall/server.ex"},{line,16}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,851}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}})

```
**To Reproduce**

1. connect to Kubernetes cluster
2. Save the yaml code above in a file
3. kubectl apply -f file.yaml
4. find the firezone pod and see the logs

**Expected behavior**
the pod should working without crashing

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version 0.7.36
 - OS: 1.25.13-gke.200 (Kubernetes Cluster)
 - Deployment method: Kubernetes
