### ISSUE TITLE
Using Docker Compose the container for Gateway keeps on starting, problem with template syntax

### ISSUE THREAD

**Issue by stevusprimus** [firezone/firezone#9226]
#### Describe the bug
Used this template and replaced the keys accordingly
https://www.firezone.dev/kb/automate/docker-compose?utm_source=product
After running `docker compose up` the conainer keeps restarting with message `login to portal failed`.
Running the container with `docker` only, like printed in the website, does not cause any issues.

The fix is to use a different syntax for the environment variables. 
Instead of using `- KEY=VALUE` use `KEY: VALUE`

```
 environment:
      # Use a unique ID for each Gateway in your Firezone account. If left blank,
      # the Gateway will generate a random ID saved in /var/lib/firezone
      # FIREZONE_ID: <id>

      # REQUIRED. The token shown when deploying a Gateway in the admin portal.
      FIREZONE_TOKEN: <token>

      # Configure log output. Other options are "trace", "debug", "info", "warn", "error", and "off".
      # See https://docs.rs/env_logger/latest/env_logger/ for more information.
      RUST_LOG: info

      # Human-friendly name to use for this Gateway in the admin portal.
      # $(hostname) is used by default if not set.
      # FIREZONE_NAME: <name-of-gateway>
```

Please correct the documentation. 

#### To Reproduce

Use the Deploy Container functionality, switch to docker.
Create a `docker-compose.yaml` file from https://www.firezone.dev/kb/automate/docker-compose?utm_source=product

#### Expected behavior

Container should not restart.

#### Screenshots / Logs

_If applicable, add screenshots and log traces to help debug your problem **with
any sensitive data removed**._

#### Platform (please complete the following information)

-  Gateway
- 1.4.9
- Debian Bookworm
- Docker 

#### Additional context

This is most likely only a documentation issue and not a software issue.
